<?php
$helper = $this->helper('Magepow\InfiniteScroll\Helper\Data');
$isEnabled = $helper->isEnabled('magepow_infinitescroll/general/enabled');
$delay = $helper->getConfigModule('magepow_infinitescroll/general/delay');
$content = $helper->getConfigModule('magepow_infinitescroll/general/content');
$pagination = $helper->getConfigModule('magepow_infinitescroll/general/pagination');
$next = $helper->getConfigModule('magepow_infinitescroll/general/next');
$item = $helper->getConfigModule('magepow_infinitescroll/general/item');
$loadingImage = '';
if ($block->getLoadingImage() != '') {
    $loadingImage = $block->getMediaPath().'/magepow/ajax_infinite_scroll/'.$block->getLoadingImage();
}else{
    $loadingImage = $this->getViewFileUrl('images/loader-1.gif');
}
$loadingText = $helper->getConfigModule('magepow_infinitescroll/general/loading_text');
$doneText = $helper->getConfigModule('magepow_infinitescroll/general/done_text');
$loadMore = $helper->getConfigModule('magepow_infinitescroll/general/load_more');
$loadMoreText = $helper->getConfigModule('magepow_infinitescroll/general/load_more_text');
if ($isEnabled) {
    ?>
    <script>
        require(['jquery', 'Magepow_InfiniteScroll/js/infinitescroll'], function ($) {
            $(document).ready(function () {
                var ias = $.ias({
                    container: "<?php echo $content;?>",
                    item: "<?php echo $item;?>",
                    pagination: "<?php echo $pagination;?>",
                    next: "<?php echo $next;?>",
                    delay: "<?php echo $delay;?>",
                });

                window.ias = $.ias();
                window.ias.extension(new IASSpinnerExtension({
                    src: "<?php echo $loadingImage; ?>",
                    html: '<div class="iass-spinner"><img src="{src}"/><p><?php echo $loadingText; ?></p></div>'
                }));

                window.ias.extension(new IASNoneLeftExtension({
                    text: "<?php echo $doneText;?>", // override text when no pages left
                    html: '<div class="ias-noneleft">{text}</div>'
                }));
               window.ias.extension(new IASTriggerExtension({
                    text:"<?php echo $loadMoreText ?>",
                    html:'<div class="ias-trigger ias-trigger-next"><button class="load-more"><?php echo $loadMoreText ?></button></div>',
                    textPrev:"<?php echo $loadMoreText ?>",
                    htmlPrev:'<div class="ias-trigger ias-trigger-prev"><button class="load-more"><?php echo $loadMoreText ?></button></div>',
                    offset:"<?php echo $loadMore ?>",
                }));
                window.ias.on('rendered', function(items){
                    $('body').trigger('contentUpdated');
                });
            });
        });
    </script>
    <?php
} ?>
<button id="infinite-scroll-top" onclick="topFunction()">Top</button>
<script>
//Get the button
var mybutton = document.getElementById("infinite-scroll-top");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>