<?php
$isEnabledAjaxInfiniteScroll = $block->isEnabled();
$delay = !empty($block->getDelay()) ? $block->getDelay() : '600';
$content = !empty($block->getContent()) ? $block->getContent() : '.main';
$pagination = !empty($block->getPagination()) ? $block->getPagination() : '.pages-items';
$next = !empty($block->getNext()) ? $block->getNext() : '.next';
$item = !empty($block->getItem()) ? $block->getItem() : '.product-item';
$loadingImage = '';
if ($block->getLoadingImage() != '') {
    $loadingImage = $block->getMediaPath().'/magepow/ajax_infinite_scroll/'.$block->getLoadingImage();
}
$loadingText = !empty($block->getLoadingText()) ? $block->getLoadingText() : '';
$doneText = !empty($block->getDoneText()) ? $block->getDoneText() : '';
$loadMore = !empty($block->getLoadMore()) ? $block->getLoadMore() : '3';
$loadMoreText = !empty($block->getLoadMoreText()) ? $block->getLoadMoreText() : 'Load more items';
if ($isEnabledAjaxInfiniteScroll) {
    ?>
    <script>
        require(['jquery', 'Magepow_InfiniteScroll/js/infinitescroll'], function ($) {
            $(document).ready(function () {
                var ias = $.ias({
                    container: "<?php echo $content;?>",
                    item: "<?php echo $item;?>",
                    pagination: "<?php echo $pagination;?>",
                    next: "<?php echo $next;?>",
                    delay: "<?php echo $delay;?>",
                });

                window.ias = $.ias();
                window.ias.extension(new IASSpinnerExtension({
                    src: "<?php echo $loadingImage; ?>",
                    html: '<div style="text-align: center;font-size: 16px;color: #333;display: block;"><img style="display:inline" src="{src}"/><p><?php echo $loadingText; ?></p></div>'
                }));

                window.ias.extension(new IASNoneLeftExtension({
                    text: "<?php echo $doneText;?>", // override text when no pages left
                    html: '<div class="ias-noneleft" style="text-align: center;color: #333;letter-spacing: 0px;font-size: 14px;font-weight: 400;">{text}</div>'
                }));
               window.ias.extension(new IASTriggerExtension({
                    text:"<?php echo $loadMoreText ?>",
                    html:'<div class="ias-trigger ias-trigger-next" style="text-align: center; cursor: pointer;"><button class="load-more" style="font-size:15px;background:#1979c3;color:#fff; border: none;width:100%;"><?php echo $loadMoreText ?></button></div>',
                    textPrev:"<?php echo $loadMoreText ?>",
                    htmlPrev:'<div class="ias-trigger ias-trigger-prev" style="text-align: center; cursor: pointer;"><button class="load-more" style="font-size:15px;background:#1979c3;color:#fff;width:100%;"><?php echo $loadMoreText ?></button></div>',
                    offset:"<?php echo $loadMore ?>",
                }));
                window.ias.on('rendered', function(items){
                    $('body').trigger('contentUpdated');
                });
            });
        });
    </script>
    <?php
} ?>
<button id="infinite-scroll-top" onclick="topFunction()">Top</button>
<script>
//Get the button
var mybutton = document.getElementById("infinite-scroll-top");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>