<?php
$helper = $this->helper('Magepow\InfiniteScroll\Helper\Data');
$isEnabled = $helper->isEnabled('general/enabled');
if( !$isEnabled ) return;
$delay = $helper->getConfigModule('general/delay');
$content = $helper->getConfigModule('general/content');
$pagination = $helper->getConfigModule('general/pagination');
$next = $helper->getConfigModule('general/next');
$item = $helper->getConfigModule('general/item');
$loadingImage = $helper->getConfigModule('general/loading_image');
if ($loadingImage) {
    $loadingImage = $block->getMedia($loadingImage);
}else{
    $loadingImage = $this->getViewFileUrl('images/loader-1.gif');
}
$loadingText = $helper->getConfigModule('general/loading_text');
$doneText = $helper->getConfigModule('general/done_text');
$loadMore = $helper->getConfigModule('general/load_more');
$loadMoreText = $helper->getConfigModule('general/load_more_text');
?>
<script>
    require(['jquery', 'magepow/infinitescroll'], function ($) {
        $(document).ready(function () {
            var ias = $.ias({
                container: "<?php echo $content;?>",
                item: "<?php echo $item;?>",
                pagination: "<?php echo $pagination;?>",
                next: "<?php echo $next;?>",
                delay: "<?php echo $delay;?>",
            });

            window.ias = $.ias();
            window.ias.extension(new IASSpinnerExtension({
                src: "<?php echo $loadingImage; ?>",
                html: '<div class="iass-spinner"><img src="{src}"/><p><?php echo $loadingText; ?></p></div>'
            }));

            window.ias.extension(new IASNoneLeftExtension({
                text: "<?php echo $doneText;?>", // override text when no pages left
                html: '<div class="ias-noneleft">{text}</div>'
            }));
           window.ias.extension(new IASTriggerExtension({
                text:"<?php echo $loadMoreText ?>",
                html:'<div class="ias-trigger ias-trigger-next"><button class="load-more"><?php echo $loadMoreText ?></button></div>',
                textPrev:"<?php echo $loadMoreText ?>",
                htmlPrev:'<div class="ias-trigger ias-trigger-prev"><button class="load-more"><?php echo $loadMoreText ?></button></div>',
                offset:"<?php echo $loadMore ?>",
            }));
            window.ias.on('rendered', function(items){
                $('body').trigger('contentUpdated');
            });
        });
    });
</script>