<?php
/**
 * @var $block Magepow\InfiniteScroll\Block\InfiniteScroll
 */

$helper = $this->helper('Magepow\InfiniteScroll\Helper\Data');
$isEnabled      = $helper->getConfigModule('general/enabled');
$delay          = $helper->getConfigModule('general/delay');
$content        = $helper->getConfigModule('general/content');
$pagination     = $helper->getConfigModule('general/pagination');
$next           = $helper->getConfigModule('general/next');
$item           = $helper->getConfigModule('general/item');
$loadingText    = $helper->getConfigModule('general/loading_text');
$doneText       = $helper->getConfigModule('general/done_text');
$loadMore       = $helper->getConfigModule('general/load_more');
$loadMoreText   = $helper->getConfigModule('general/load_more_text');
$loadingImage   = $helper->getConfigModule('general/loading_image');
$imgPath        = 'magepow/infinitescroll/'. $loadingImage;
if ($loadingImage) {
    $loadingImage = $block->getMedia($imgPath);
} else {
    $loadingImage = $this->getViewFileUrl('images/loader-1.gif');
}
?>
<script type="text/javascript">
    require(['jquery', 'magepow/infinitescroll', 'catalogAddToCart'], function ($) {
        "use strict";
        $('body').addClass('infinitescroll');
        $(window).on('collectionUpdated', function () {
            if(jQuery().ias) {
                $.ias('destroy');
            }
            window.ias = $.ias({
                container: "<?=  $content ?>",
                item: "<?= $item ?>",
                pagination: "<?= $pagination ?>",
                next: "<?= $next ?>",
                delay: "<?= $delay ?>",
            });
            window.ias.extension(new IASSpinnerExtension({
                src: "<?= $loadingImage ?>",
                html: '<div class="iass-spinner"><img src="{src}"/><span><?= $loadingText ?></span></div>'
            }));
            window.ias.extension(new IASNoneLeftExtension({
                text: "<?= $doneText ?>",
                html: '<div class="ias-noneleft">{text}</div>'
            }));
            window.ias.extension(new IASTriggerExtension({
                text: "<?= $loadMoreText ?>",
                html: '<div class="ias-trigger ias-trigger-next"><button class="load-more"><?= $loadMoreText ?></button></div>',
                textPrev: "<?= $loadMoreText ?>",
                htmlPrev: '<div class="ias-trigger ias-trigger-prev"><button class="load-more"><?= $loadMoreText ?></button></div>',
                offset: <?php echo ($loadMore > 0) ? $loadMore: 'false'  ?>,
            }));
            window.ias.on('rendered', function (items) {
                $('body').trigger('contentUpdated');
                $("form[data-role='tocart-form']").catalogAddToCart();
            });

        });
        $(document).ready(function () {
            $('body').trigger('collectionUpdated');
        });
    });
</script>
